---
title: "An Analysis of the Gender Pay Gap in UK Univerisities"
author: "Matthew Knowles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/home/matthew/Documents/EDA_CS1")
library(ggplot2)
library(dplyr)
library(mice)
library(finalfit)

# Load Data
GPG1718 <- read.csv(file = "data/GPG1718.csv")
GPG1819 <- read.csv(file = "data/GPG1819.csv")
GPG1920 <- read.csv(file = "data/GPG1920.csv")
GPG2021 <- read.csv(file = "data/GPG2021.csv")
GPG2122 <- read.csv(file = "data/GPG2122.csv")
unis <- read.csv("data/universities.csv")

# Add a year coolumn to each data
GPG1718$year <- 2017
GPG1819$year <- 2018
GPG1920$year <- 2019
GPG2021$year <- 2020
GPG2122$year <- 2021

# Compile data
GPG <- rbind(GPG1718, GPG1819, GPG1920, GPG2021, GPG2122)

# Just University GPG data
uniGPG <- GPG %>%
    filter(EmployerName %in% unis$EmployerName)

# Get the count of reporting
uni_year_count <- uniGPG %>%
    count(EmployerName)

# Plot the density of reporting frequency
uni_year_count_density <- density(uni_year_count$n)
plot(uni_year_count_density)
```

# Introduction

Here, we will take a look at the Gender Pay Gap in the UK. Specifically, in UK universities.

# Data Overview

## Missing Data

Missing data is a common problem in data analysis. 

```{r, echo = FALSE, results = 'hide'}
md.pattern(uniGPG, rotate.names = TRUE)
```

We see that the two missing datapoints are the difference in mean and median bonus percent.

```{r, echo = FALSE}
uniGPG <- na.omit(uniGPG)
```

# Densities

```{r}
ggplot(uniGPG, aes(x = DiffMedianHourlyPercent)) +
    geom_density(data = filter(uniGPG, year == 2017), fill = "lightblue") +
    geom_density(data = filter(uniGPG, year == 2018), fill = "pink", alpha = 0.3) + 
    geom_density(data = filter(uniGPG, year == 2019), fill = "lightgreen", alpha = 0.3) + 
    geom_density(data = filter(uniGPG, year == 2020), fill = "blue", alpha = 0.3) + 
    geom_density(data = filter(uniGPG, year == 2021), fill = "magenta", alpha = 0.3) +
    geom_density(data = filter(uniGPG, year == 2012), fill = "yellow", alpha = 0.3)

```
